### ISSUE TITLE
Live instance not working properly

### ISSUE THREAD

**Issue by akien-mga** [howlowck/quarto#1]
Hi there,

I've tried to play on http://www.lifeishao.com/quarto with a friend, but it does not seem to work properly:
- The server seems pretty slow (that might just be a server side issue though and not related to the game)
- On Firefox, it's possible to grab the piece from the waiting area and place it, but then after "Next move" it's not possible to select a piece for the opponent, so the game is stalled.
- On Chromium, it seems that starting a game does not work at all

**Comment by howlowck** [comment]
Hey! Thanks for playing and letting me know!  The node server was housed on Nodejitsu.  but based on [this blog post](https://blog.nodejitsu.com/nodejitsu-joins-godaddy/) they are no longer supporting node hosting as a PaaS.  They were gracious enough to host this project for free because it's open source.  So now I have to find another service that would do the same...  Stay tuned, hopefully I'll find one soon.

**Comment by akien-mga** [comment]
Thanks for looking into this! :)

**Comment by howlowck** [comment]
It's fixed now.  You can go back to www.lifeishao.com/quarto and it should work.

**Comment by akien-mga** [comment]
It works somewhat better, but there are still issues after the first move is played, with player2 I get attempts to be redirected to http://www.dlrh.com/ or http://www.wlrh.com/

**Comment by howlowck** [comment]
There seems to be some browser bugs that does that when I first started developing the game, and it stopped when I used Chrome or Firefox.   If the problem persists on modern browsers, open a new issue.
